language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
# command to run tests
script:
  - pipenv run pycodestyle
  - pipenv run coverage run -m pytest
after_success:
  - codecov
