DROP TABLE IF EXISTS feature_flags;

CREATE TABLE feature_flags (
    key TEXT UNIQUE NOT NULL,
    active INTEGER NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);
